# DigitalOcean App Platform Configuration
# This file defines the deployment configuration for the MMS (Maintenance Management System)
# 
# IMPORTANT: Before deploying, you must:
# 1. Update all environment variables with your actual values
# 2. Configure your domain settings in DigitalOcean
# 3. Set up any required secrets in the App Platform console
# 4. Consider using DigitalOcean Spaces instead of MinIO for object storage

name: mms-app
region: nyc

# ============================================================================
# SERVICES
# ============================================================================

services:
  # --------------------------------------------------------------------------
  # Frontend Service (React + Nginx)
  # --------------------------------------------------------------------------
  - name: frontend
    # Build configuration
    github:
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
      branch: main
      deploy_on_push: true
    source_dir: /CMMS_/frontend
    dockerfile_path: CMMS_/frontend/Dockerfile
    
    # Resource configuration
    instance_count: 1
    instance_size_slug: basic-xxs
    
    # HTTP configuration
    http_port: 3000
    
    # Routes
    routes:
      - path: /
    
    # Environment variables
    envs:
      - key: API_URL
        value: ${api.PUBLIC_URL}/api
      - key: GOOGLE_KEY
        value: ""
      - key: GOOGLE_TRACKING_ID
        value: ""
      - key: MUI_X_LICENSE
        value: "e0d9bb8070ce0054c9d9ecb6e82cb58fTz0wLEU9MzI0NzIxNDQwMDAwMDAsUz1wcmVtaXVtLExNPXBlcnBldHVhbCxLVj0y"
      - key: INVITATION_VIA_EMAIL
        value: "false"
      - key: CLOUD_VERSION
        value: "true"
      - key: NODE_ENV
        value: "production"
      - key: ENABLE_SSO
        value: "false"
      - key: OAUTH2_PROVIDER
        value: ""
      - key: LOGO_PATHS
        value: ""
      - key: CUSTOM_COLORS
        value: ""
      - key: BRAND_CONFIG
        value: ""
      - key: DEMO_LINK
        value: ""
    
    # Health check
    health_check:
      http_path: /
      initial_delay_seconds: 60
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

  # --------------------------------------------------------------------------
  # API Service (Spring Boot Backend)
  # --------------------------------------------------------------------------
  - name: api
    # Build configuration
    github:
      repo: YOUR_GITHUB_USERNAME/YOUR_REPO_NAME
      branch: main
      deploy_on_push: true
    source_dir: /CMMS_/api
    dockerfile_path: CMMS_/api/Dockerfile
    
    # Resource configuration
    instance_count: 1
    instance_size_slug: basic-xs
    
    # HTTP configuration
    http_port: 8080
    
    # Routes
    routes:
      - path: /api
    
    # Environment variables
    envs:
      # Database configuration (uses managed database)
      - key: DB_URL
        value: ${db.HOSTNAME}:${db.PORT}/${db.DATABASE}
      - key: DB_USER
        value: ${db.USERNAME}
      - key: DB_PWD
        value: ${db.PASSWORD}
      
      # Public URLs
      - key: PUBLIC_API_URL
        value: ${_self.PUBLIC_URL}/api
      - key: PUBLIC_FRONT_URL
        value: ${frontend.PUBLIC_URL}
      - key: frontend.url
        value: ${frontend.PUBLIC_URL}
      
      # Security
      - key: JWT_SECRET_KEY
        type: SECRET
        value: "CHANGE_THIS_JWT_SECRET_IN_PRODUCTION"
      
      # Spring Boot profile
      - key: SPRING_PROFILES_ACTIVE
        value: "prod"
      
      # Email Configuration
      - key: SMTP_HOST
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        type: SECRET
        value: ""
      - key: SMTP_PWD
        type: SECRET
        value: ""
      - key: MAIL_RECIPIENTS
        value: ""
      - key: INVITATION_VIA_EMAIL
        value: "false"
      - key: ENABLE_EMAIL_NOTIFICATIONS
        value: "false"
      
      # Storage Configuration (MinIO)
      - key: STORAGE_TYPE
        value: "minio"
      - key: MINIO_ENDPOINT
        value: "http://${minio.PRIVATE_URL}:9000"
      - key: PUBLIC_MINIO_ENDPOINT
        value: "${minio.PUBLIC_URL}"
      - key: MINIO_BUCKET
        value: "mms-bucket"
      - key: MINIO_ACCESS_KEY
        type: SECRET
        value: "minio"
      - key: MINIO_SECRET_KEY
        type: SECRET
        value: "minio123"
      
      # GCP Storage (Alternative to MinIO)
      - key: GCP_BUCKET_NAME
        value: ""
      - key: GCP_JSON
        type: SECRET
        value: ""
      - key: GCP_PROJECT_ID
        value: ""
      
      # FastSpring Configuration
      - key: FASTSPRING_USER
        type: SECRET
        value: ""
      - key: FASTSPRING_PWD
        type: SECRET
        value: ""
      
      # SSO Configuration
      - key: ENABLE_SSO
        value: "false"
      - key: OAUTH2_PROVIDER
        value: ""
      - key: OAUTH2_CLIENT_ID
        type: SECRET
        value: ""
      - key: OAUTH2_CLIENT_SECRET
        type: SECRET
        value: ""
      
      # License Configuration
      - key: LICENSE_KEY
        type: SECRET
        value: ""
      - key: LICENSE_FINGERPRINT_REQUIRED
        value: "false"
      - key: ALLOWED_ORGANIZATION_ADMINS
        value: ""
      
      # Branding
      - key: LOGO_PATHS
        value: ""
      - key: CUSTOM_COLORS
        value: ""
      - key: BRAND_CONFIG
        value: ""
    
    # Health check
    health_check:
      http_path: /api/actuator/health
      initial_delay_seconds: 90
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

  # --------------------------------------------------------------------------
  # MinIO Service (Object Storage)
  # --------------------------------------------------------------------------
  # NOTE: Consider using DigitalOcean Spaces instead for better reliability
  # and managed storage. MinIO in App Platform may not persist data reliably.
  - name: minio
    # Image configuration
    image:
      registry_type: DOCKER_HUB
      registry: minio
      repository: minio
      tag: RELEASE.2025-04-22T22-12-26Z
    
    # Resource configuration
    instance_count: 1
    instance_size_slug: basic-xxs
    
    # HTTP configuration
    http_port: 9000
    
    # Routes
    routes:
      - path: /minio
    
    # Environment variables
    envs:
      - key: MINIO_ROOT_USER
        type: SECRET
        value: "minio"
      - key: MINIO_ROOT_PASSWORD
        type: SECRET
        value: "minio123"
    
    # Run command
    run_command: "server --address \":9000\" --console-address \":9001\" /data"
    
    # Health check
    health_check:
      http_path: /minio/health/live
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

  # --------------------------------------------------------------------------
  # InfluxDB Service (Time Series Database)
  # --------------------------------------------------------------------------
  - name: influxdb
    # Image configuration
    image:
      registry_type: DOCKER_HUB
      registry: influxdb
      repository: influxdb
      tag: "2.8"
    
    # Resource configuration
    instance_count: 1
    instance_size_slug: basic-xs
    
    # HTTP configuration
    http_port: 8086
    
    # Routes
    routes:
      - path: /influxdb
    
    # Environment variables
    envs:
      - key: DOCKER_INFLUXDB_INIT_MODE
        value: "setup"
      - key: DOCKER_INFLUXDB_INIT_USERNAME
        value: "admin"
      - key: DOCKER_INFLUXDB_INIT_PASSWORD
        type: SECRET
        value: "securepassword"
      - key: DOCKER_INFLUXDB_INIT_ORG
        value: "mms"
      - key: DOCKER_INFLUXDB_INIT_BUCKET
        value: "assets"
      - key: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
        type: SECRET
        value: "my-super-secret-influxdb-token-change-me"
      - key: INFLUXDB_HTTP_BIND_ADDRESS
        value: ":8086"
      - key: INFLUXDB_REPORTING_DISABLED
        value: "true"
    
    # Health check
    health_check:
      http_path: /influxdb/health
      initial_delay_seconds: 60
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

  # --------------------------------------------------------------------------
  # Grafana Service (Visualization & Analytics)
  # --------------------------------------------------------------------------
  - name: grafana
    # Image configuration
    image:
      registry_type: DOCKER_HUB
      registry: grafana
      repository: grafana
      tag: "latest"
    
    # Resource configuration
    instance_count: 1
    instance_size_slug: basic-xxs
    
    # HTTP configuration
    http_port: 3000
    
    # Routes
    routes:
      - path: /grafana
    
    # Environment variables
    envs:
      - key: GF_SECURITY_ADMIN_USER
        value: "admin"
      - key: GF_SECURITY_ADMIN_PASSWORD
        type: SECRET
        value: "adminpassword"
      - key: GF_AUTH_ANONYMOUS_ENABLED
        value: "true"
      - key: GF_AUTH_ANONYMOUS_ORG_ROLE
        value: "Viewer"
      - key: GF_SERVER_DOMAIN
        value: "${_self.PUBLIC_URL}"
      - key: GF_SERVER_ROOT_URL
        value: "${_self.PUBLIC_URL}/grafana/"
      - key: GF_SERVER_SERVE_FROM_SUB_PATH
        value: "true"
      - key: GF_INSTALL_PLUGINS
        value: ""
      - key: INFLUXDB_ADMIN_TOKEN
        type: SECRET
        value: "my-super-secret-influxdb-token-change-me"
      - key: POSTGRES_USER
        value: ${db.USERNAME}
      - key: POSTGRES_PWD
        value: ${db.PASSWORD}
    
    # Health check
    health_check:
      http_path: /grafana/api/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

# ============================================================================
# DATABASES
# ============================================================================

databases:
  # Managed PostgreSQL Database
  - name: db
    engine: PG
    version: "16"
    production: false  # Set to true for production deployments
    cluster_name: mms-db-cluster
    db_name: mms
    db_user: rootUser

# ============================================================================
# DEPLOYMENT NOTES
# ============================================================================
# 
# 1. UPDATE GITHUB REPOSITORY:
#    Replace YOUR_GITHUB_USERNAME/YOUR_REPO_NAME with your actual repo
# 
# 2. UPDATE SECRETS:
#    All environment variables marked as SECRET should be updated with actual values
#    in the DigitalOcean App Platform console for security.
# 
# 3. STORAGE CONSIDERATIONS:
#    - MinIO in App Platform may not persist data reliably between deployments
#    - Consider using DigitalOcean Spaces (S3-compatible) for production
#    - Update STORAGE_TYPE to "gcp" and configure GCP_* variables if using Spaces
# 
# 4. DATABASE PERSISTENCE:
#    - The managed PostgreSQL database will persist data automatically
#    - InfluxDB data may be lost on redeployment (consider managed time-series DB)
# 
# 5. DOMAIN CONFIGURATION:
#    - Configure your custom domain in the App Platform console
#    - Update PUBLIC_API_URL and PUBLIC_FRONT_URL accordingly
#    - Enable HTTPS/SSL certificates through App Platform
# 
# 6. RESOURCE SIZING:
#    - Adjust instance_size_slug based on your traffic and performance needs
#    - Available sizes: basic-xxs, basic-xs, basic-s, basic-m, professional-xs, etc.
# 
# 7. MONITORING:
#    - Health checks are configured for all services
#    - Use DigitalOcean's monitoring dashboard for insights
#    - Consider setting up alerts for service failures
# 
# 8. COST OPTIMIZATION:
#    - Start with smaller instance sizes and scale up as needed
#    - Use production: false for the database during development/testing
#    - Monitor your App Platform usage and costs regularly
# 
# 9. GRAFANA PROVISIONING:
#    - The grafana/provisioning directory from docker-compose won't work in App Platform
#    - You may need to configure datasources manually or use Grafana's API
# 
# 10. NGINX PROXY:
#     - Not included in this config as App Platform handles routing natively
#     - Each service is exposed on its own route (/api, /grafana, /influxdb, /minio)
# 
# ============================================================================
